services:
  mysql:
    image: mysql:8.0
    container_name: user-ms
    env_file:
      - .env
    environment:
      MYSQL_DATASOURCE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DB_PORT_EXTERNAL}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data: